// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for detecting potentially fraudulent withdrawal requests.
 *
 * It uses AI to analyze user behavior, withdrawal patterns, and other relevant factors.
 * The flow takes a WithdrawalRequestInput as input and returns a FraudulentWithdrawalOutput indicating whether the withdrawal is potentially fraudulent.
 *
 * @file
 * - fraudulentWithdrawalDetection - Function to detect fraudulent withdrawal requests.
 * - WithdrawalRequestInput - Input type for the fraudulentWithdrawalDetection function.
 * - FraudulentWithdrawalOutput - Return type for the fraudulentWithdrawalDetection function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const WithdrawalRequestInputSchema = z.object({
  userId: z.string().describe('The ID of the user requesting the withdrawal.'),
  withdrawalAmount: z.number().describe('The amount the user is requesting to withdraw.'),
  withdrawalMethod: z.string().describe('The method the user is using to withdraw funds (e.g., bank transfer, cryptocurrency).'),
  userAccountAgeDays: z.number().describe('The age of the user account in days.'),
  transactionHistory: z.string().describe('A stringified JSON array of recent transaction history for the user.'),
  averageDailyWithdrawal: z.number().describe('Average daily withdrawal amount of the user in the past 30 days'),
  ipAddress: z.string().describe('The IP address from which the withdrawal request originated.'),
  location: z.string().describe('The geographical location from which the withdrawal request originated.'),
});
export type WithdrawalRequestInput = z.infer<typeof WithdrawalRequestInputSchema>;

const FraudulentWithdrawalOutputSchema = z.object({
  isFraudulent: z.boolean().describe('Whether the withdrawal request is potentially fraudulent.'),
  fraudExplanation: z.string().describe('Explanation of why the withdrawal request is considered potentially fraudulent.'),
  confidenceScore: z.number().describe('Confidence score (0-1) indicating the likelihood of fraud.'),
});
export type FraudulentWithdrawalOutput = z.infer<typeof FraudulentWithdrawalOutputSchema>;

export async function fraudulentWithdrawalDetection(input: WithdrawalRequestInput): Promise<FraudulentWithdrawalOutput> {
  return fraudulentWithdrawalDetectionFlow(input);
}

const fraudulentWithdrawalDetectionPrompt = ai.definePrompt({
  name: 'fraudulentWithdrawalDetectionPrompt',
  input: {schema: WithdrawalRequestInputSchema},
  output: {schema: FraudulentWithdrawalOutputSchema},
  prompt: `You are a fraud detection expert. Analyze the following withdrawal request and determine if it is potentially fraudulent.

  User ID: {{{userId}}}
  Withdrawal Amount: {{{withdrawalAmount}}}
  Withdrawal Method: {{{withdrawalMethod}}}
  User Account Age (Days): {{{userAccountAgeDays}}}
  Transaction History: {{{transactionHistory}}}
  Average Daily Withdrawal: {{{averageDailyWithdrawal}}}
  IP Address: {{{ipAddress}}}
  Location: {{{location}}}

  Based on this information, determine if the withdrawal request is fraudulent. Explain your reasoning and provide a confidence score (0-1).
  Set the isFraudulent field accordingly.

  Respond in a valid JSON format.
  `,
});

const fraudulentWithdrawalDetectionFlow = ai.defineFlow(
  {
    name: 'fraudulentWithdrawalDetectionFlow',
    inputSchema: WithdrawalRequestInputSchema,
    outputSchema: FraudulentWithdrawalOutputSchema,
  },
  async input => {
    const {output} = await fraudulentWithdrawalDetectionPrompt(input);
    return output!;
  }
);
