// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for determining referral income allocation.
 *
 * The flow takes into account user levels, system conditions, and referral success rates
 * to optimize the referral program for growth and sustainability.
 *
 * @interface ReferralIncomeAllocationInput - Defines the input schema for the referral income allocation flow.
 * @interface ReferralIncomeAllocationOutput - Defines the output schema for the referral income allocation flow.
 * @function allocateReferralIncome - The main function to trigger the referral income allocation flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReferralIncomeAllocationInputSchema = z.object({
  userLevel: z
    .string()
    .describe(
      'The level of the user making the referral (e.g., Bronze, Silver, Gold).' // removed example values as they were being interpreted as hard constraints
    ),
  systemConditions: z
    .string()
    .describe(
      'The current system conditions (e.g., High Traffic, Low Engagement).' // removed example values as they were being interpreted as hard constraints
    ),
  referralSuccessRate: z
    .number()
    .describe(
      'The historical success rate of referrals made by this user (0 to 1).' // removed example values as they were being interpreted as hard constraints
    ),
  totalInvestment: z
    .number()
    .describe('The total investment amount made by the referred user.'),
});

export type ReferralIncomeAllocationInput = z.infer<
  typeof ReferralIncomeAllocationInputSchema
>;

const ReferralIncomeAllocationOutputSchema = z.object({
  referralIncomePercentage: z
    .number()
    .describe(
      'The recommended referral income percentage to allocate for this referral.'
    ),
  reasoning: z
    .string()
    .describe(
      'The detailed reasoning behind the allocated referral income percentage.'
    ),
});

export type ReferralIncomeAllocationOutput = z.infer<
  typeof ReferralIncomeAllocationOutputSchema
>;

export async function allocateReferralIncome(
  input: ReferralIncomeAllocationInput
): Promise<ReferralIncomeAllocationOutput> {
  return referralIncomeAllocationFlow(input);
}

const referralIncomeAllocationPrompt = ai.definePrompt({
  name: 'referralIncomeAllocationPrompt',
  input: {schema: ReferralIncomeAllocationInputSchema},
  output: {schema: ReferralIncomeAllocationOutputSchema},
  prompt: `You are an AI-powered referral program optimization expert.
  Given the following information about a user referral, determine the optimal referral income percentage to allocate to the referring user.

  User Level: {{{userLevel}}}
  System Conditions: {{{systemConditions}}}
  Referral Success Rate: {{{referralSuccessRate}}}
  Total Investment: {{{totalInvestment}}}

  Consider the following factors when determining the referral income percentage:
  - User Level: Higher-level users may be eligible for higher referral percentages.
  - System Conditions: During periods of low engagement, consider increasing referral percentages to incentivize growth. During high traffic, consider decreasing referral percentages to maintain sustainability.
  - Referral Success Rate: Users with a higher referral success rate may be rewarded with higher percentages.
  - Total Investment: The referral percentage could be scaled according to the total investment of the referred user.

  Provide a referralIncomePercentage and reasoning for your decision.
  `,
});

const referralIncomeAllocationFlow = ai.defineFlow(
  {
    name: 'referralIncomeAllocationFlow',
    inputSchema: ReferralIncomeAllocationInputSchema,
    outputSchema: ReferralIncomeAllocationOutputSchema,
  },
  async input => {
    const {output} = await referralIncomeAllocationPrompt(input);
    return output!;
  }
);
